name: Linter and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: true
    
    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
